# Generated by Django 4.1.4 on 2022-12-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.DecimalField(decimal_places=2, max_digits=3)),
                ('desc', models.CharField(max_length=255)),
            ],
        ),
    ]
